---
title: "r_int_day_1_r_basic_sumstat"
author: "Nicholus Tint Zaw"
date: "2022-10-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Content 

1. r - base commands for Summary Statistics 
1. loading data files  
1. exercises 





## r - base commands for Summary Statistics 

```{r}
# load r-bulit-in dataset 

df <- iris

# datafile summary 
summary(df)

# mean 
mean(df$Sepal.Length)

# SD
sd(df$Sepal.Length)

# median
median(df$Sepal.Length)

# percentile 
quantile(df$Sepal.Width, 0.1)

quantile(df$Petal.Length, c(0.1, 0.9))

quantile(df$Petal.Length, seq(0, 1, by = 0.1))

# quartile
quantile(df$Petal.Length, seq(0, 1, by = 0.25))

# IQR
IQR(df$Petal.Width)

quantile(df$Petal.Width, 0.75) - quantile(df$Petal.Width, 0.25)

```



## loading data files  

```{r}
# load csv 
df <- read.csv("wnba.csv")


# excel file 
library("readxl")

df_2 <- read_excel("wnba.xlsx", sheet = "wnba")

```



## exercises 

In a Science test, each correct answer was awarded 5 marks and 2 marks were deducted for each incorrect answer. If there were 20 questions in the test and Danny obtained 79 marks, how many questions did he answer correctly? 




